name: remember
description: A simple brain game
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons:
  path_provider:
  global_configuration:
  audioplayers:
  flutter_page_transition:
  confetti:
  awesome_dialog:
  devicelocale:
  rate_my_app:
  flare_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lang/


